apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments 
  template:
    metadata:
      labels:
        app: payments 
    spec:
      containers:
        - name: payments 
          image: harish3005/payment
          env:
            - name: MONGO_URI
              value: 'mongodb://localhost:27017/ctse'           
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  type: ClusterIP
  selector:
    app: payments 
  ports:
    - name: payments 
      protocol: TCP
      port: 8081
      targetPort: 8081